### ISSUE TITLE
LU Underground mod looks for a non-existent version of MTR mod

### ISSUE THREAD

**Issue by Chozermith** [cherbert/mtr-london-underground-addon#18]
![Знімок екрана 2024-06-22 121706](https://github.com/cherbert/mtr-london-underground-addon/assets/172991311/bf8f609e-d0d7-48d4-b1cb-2f4cdc305a59)
LU Underground extension mod looks for a MTR mod version that doesn't exist.

**Comment by AwesomeKalin** [comment]
4.0 Beta 8 does exist

**Comment by cherbert** [comment]
facepalm

**Comment by Chozermith** [comment]
If there's nothing wrong here, could you please explain me what I did wrong?

**Comment by cherbert** [comment]
You are trying to run a version of the LU mod designed for MTR 4.0 beta 8. You claimed 4.0 beta doesn't exist. It does. Either update your MTR to 4.0 beta 8 or remove the LU addon v2.2.0 and install the LU addon 2.1.2

**Comment by Chozermith** [comment]
Oh okay thanks
